"""Install devman's static assets into a consumer repo + record a manifest.

Mirrors :func:`repoman.skills.install_entrypoint`'s contract (returns the written
paths). Skills land beside the generated entrypoint skill under ``skills_dir``; the
docs export and articles land under ``docs_dir``. A manifest (``.devman-source``)
records the repoman version + shipped skill list so ``repoman doctor`` can detect
drift — the allium-env ``.allium-devenv-source`` pattern.
"""

from __future__ import annotations

import shutil
from importlib.metadata import version
from pathlib import Path

from .assets import ARTICLES_SRC, DOCS_SRC, SKILLS_SRC, expected_skills

MANIFEST = ".devman-source"


def install_devman(skills_dir: str, docs_dir: str, repo_root: str) -> list[Path]:
    """Copy devman's skills + docs + articles into ``repo_root`` and write a manifest."""

    root = Path(repo_root)
    written: list[Path] = []

    # Skills → <repo>/<skills_dir>/<name>/SKILL.md (siblings of the entrypoint skill).
    skills_root = root / skills_dir
    for name in expected_skills():
        dest = skills_root / name
        dest.mkdir(parents=True, exist_ok=True)
        shutil.copy2(SKILLS_SRC / name / "SKILL.md", dest / "SKILL.md")
        written.append(dest / "SKILL.md")

    # Docs export → <repo>/<docs_dir>/*.md; articles → <repo>/<docs_dir>/articles/*.md.
    docs_root = root / docs_dir
    for src_dir, sub in ((DOCS_SRC, ""), (ARTICLES_SRC, "articles")):
        if not src_dir.is_dir():
            continue
        target = docs_root / sub if sub else docs_root
        target.mkdir(parents=True, exist_ok=True)
        for md in sorted(src_dir.glob("*.md")):
            shutil.copy2(md, target / md.name)
            written.append(target / md.name)

    # Manifest (drift detection: version + source list).
    manifest = skills_root / MANIFEST
    manifest.parent.mkdir(parents=True, exist_ok=True)
    manifest.write_text(
        "Generated by repoman (devman subsystem).\n"
        f"repoman version: {version('repoman')}\n"
        f"skills: {', '.join(expected_skills())}\n"
        "Do not edit these copies; update repoman and re-run `repoman install-skills`.\n"
    )
    written.append(manifest)
    return written
